[project]
name = "markdown-notes"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "AbedAlRahman-Bakir", email = "abedalrahmanbakir@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.141.1",
    "markdown>=3.10.3",
    "nh3>=0.3.7",
    "python-multipart>=0.0.32",
    "uvicorn[standard]>=0.53.0",
]

[project.scripts]
markdown-notes = "markdown_notes:main"

[build-system]
requires = ["uv_build>=0.12.7,<0.13.0"]
build-backend = "uv_build"
